# Service for the frontend.
# The Ingress routes external traffic here.
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: esg
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
