---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
  namespace: esg
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgAup1PZqMB8RMNeDzKOrPgkXTTni3SFtQvpb7Yw7ZP2EpIcls7m5ZojlXHY3NE4Dw4nred2lUsTNh3PTmJ24AuT3fWDtKpL+EaoZQi+35BgqavqGIcnmh7w3hKVQSfwZ6JG1Lt2WYEXnasR7ywKveRa+N6aUE9Sy6IOhYVsF5Qqw6cM/uTGscYoZLj5+oN5cu+T5r/O2K+IvAoblYlRMpDwl8b0ORy7bDQ+9oxdh84z0QCqyCEECThochVb12rCAbuDXqX1AU70J3rJkGjPwbVjYGJbB6ku6tBScQSozVIOrwvpW/Uo1a7scw7V54s3n9cHjAXtBY3a9Ea+BJZS/V+e0owHA3t3jFtLLfipBKcOGn2/aMOkmG4dec9LgH0IXsIRdMxANTPDSMPOa7qvbI25GpiVodveojQF7OnyWVEhNf6lh6vkDbhRKsmQoU6detrA2Wf15A8VqQktJCptGlMR3kjs+xK/J1beMarFrBRfsBwn8K3LloH/cl/ZmzibegYgErrPuWq9JH2goea1YTQQ6rQ39O5BNTwUrz9KhzNcV1cQxousfUySUYsrBG/HvnpIU0Ux5GPVDHuJK6FfK+13SJrzk9UzxaO0MsTzShFVVJ1eCWDtG0FqjPcZpXfH4/evt2KE0o6w7vWvpXO22vhcD430/eTLDnc4B5mg7hrLrtMkGxwu3yOzrm3PoaQNbnOgGjt7FFGMjJlmd7Zo
    MINIO_ROOT_USER: AgASdsgQp8t+GAyMq6djJ3QCZ6oAxkkwMsrw5WEPQAF6TTk8Pr4i/U8OiREOkeW+KJC3NhG1IMR+GepMjAVVevNwbUS+83sKMOBPkcML6vrX67lmLCeG4UG6Zy0gLhLXPNyY3JdNiH4BnF7aB5p0CYz4x1TPPNimYJHZED1dzsAEAlZX/kpYfGLGGDeqI/cBk6V3g15aV+5xrYL2bdJy9hrQu8YYZre1oSvJBHdoBwsNy/j/IfkQy4TC805ZlJti/g/XetaTOe3jbu/ozUrpcCOwIUfhUi/lFnUjKWl4+3CJ3mUaQgPIY96RITKfQF8yJdVa2wQA4nlSWG0wbz17gFlUWDPHan1olhqDhAr4Uht+7gKeo3g8pauRb6gRAJJBJA04vA8r0KppNOGuizJiHnrRqPZiil1y2yv6KvoQIXXEbqVUTfx6m+zRTHeiOWXC14fdAj8u148I2mwALGvOD52qsRvx5q71qsnaKnPVMriPquvMpy9leVkFQ8SqKl6PQ6Y/uM4mTsVepGP5lz5rfLrltf6USLbTn2nNfjkSlCkTrCR2MU70TSuy9hn/7dOSUw7rdC5qcD1veXblF7EtelJXcp+DOuH+4kY9dUsQTYa1B0Az/I7K777KPB3V7odkBB0rgo2QnIVKQpBjpeKOpqAK3hWHg6Hx8unuO8kM96wFxKRA6L5ID9pDOljES88B1pGHUB40f4YaHBUX
  template:
    metadata:
      name: minio-secret
      namespace: esg
