apiVersion: v1
kind: Service
metadata:
  name: minio-svc   # backend 用 "minio-svc:9000" 連進來
  namespace: esg
spec:
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
