apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: esg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: mongodb-secret   # MONGO_INITDB_ROOT_USERNAME/PASSWORD
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db      # MongoDB 預設資料路徑
          readinessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc    # 掛載剛才建立的磁碟空間
