apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc   # backend 用 "mongodb-svc:27017" 連進來
  namespace: esg
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
